# USAGE:
#   BUILD:
#     Defaults:
#     podman build --build-arg-file defaults.conf --build-arg-file=CONFNAME.conf --secret=id=bw_clientid,env=BW_CLIENTID --secret=id=bw_clientsecret,env=BW_CLIENTSECRET -t hdub-tech/bwdc-gsuite-CONFNAME:VERSION_OF_THIS_IMAGE -f Containerfile
#
#     Overrides:
#     podman build --build-arg-file custom.conf --build-arg-file=CONFNAME.conf --secret=id=bw_clientid,env=BW_CLIENTID --secret=id=bw_clientsecret,env=BW_CLIENTSECRET -t hdub-tech/bwdc-gsuite-CONFNAME:VERSION_OF_THIS_IMAGE -f Containerfile
#
#   RUN:
#     Non-interactively:
#     podman run --env-file $BITWARDENCLI_CONNECTOR_DIRECTORY_TYPE/env.vars --rm hdub-tech/bwdc-gsuite-CONFNAME:VERSION_OF_THIS_IMAGE [-h] [-c] [-t] [-s]
#
#     Interactively:
#     podman run --env-file $BITWARDENCLI_CONNECTOR_DIRECTORY_TYPE/env.vars --rm -it --entrypoint bash hdub-tech/bwdc-gsuite-CONFNAME:VERSION_OF_THIS_IMAGE
#    bitwarden@deadbeef1234:~$ ./entrypoint -h  #List help for container script
#    bitwarden@deadbeef1234:~$ bwdc help        #Use raw bwdc cli
#
ARG BWDC_VERSION
FROM ghcr.io/hdub-tech/bwdc-base:$BWDC_VERSION

ARG BWDC_GSUITE_IMAGE_VERSION="dev"
ENV BITWARDENCLI_CONNECTOR_DIRECTORY_TYPE=gsuite
ARG CONFNAME
LABEL org.opencontainers.image.title="bwdc-${BITWARDENCLI_CONNECTOR_DIRECTORY_TYPE}-${CONFNAME}"
LABEL org.opencontainers.image.description="Image built off bwdc-base with a data.json specific to ${BITWARDENCLI_CONNECTOR_DIRECTORY_TYPE}/${CONFNAME}.conf"
LABEL org.opencontainers.image.authors="hdub-tech@github"
LABEL org.opencontainers.image.source="https://github.com/hdub-tech/bitwarden-directory-connector-containers/blob/main/gsuite/Containerfile"
LABEL org.opencontainers.image.licenses="GPL-3.0"
LABEL org.opencontainers.image.version=$BWDC_GSUITE_IMAGE_VERSION

# User
ARG BWUSER=bitwarden
ARG BWUID=1000
USER $BWUSER

# Configurable arguments (Use $REPO/$TYPE/argfile.conf for overrides)
ARG GOOGLE_DOMAIN
ARG GOOGLE_ADMIN_USER_EMAIL
ARG GOOGLE_CUSTOMER=""
ARG GOOGLE_SERVICE_USER_EMAIL
ARG GOOGLE_SYNC_USERS=false
ARG GOOGLE_SYNC_USER_FILTER=""
ARG GOOGLE_SYNC_GROUPS=false
ARG GOOGLE_SYNC_GROUP_FILTER=""
ARG GOOGLE_SYNC_REMOVE_DISABLED=false
ARG GOOGLE_SYNC_OVERWRITE_EXISTING=false
ARG GOOGLE_SYNC_LARGE_IMPORT=false

# Copy in the sync block
COPY --chown=$BWUID:$BWUID --chmod=700 sync.json $WORKING_DIR/

ARG OPTIONAL_REBUILD_BWDC_LOGIN_STAGE
# Run login to initialize the data.json file. bwdc config only works when
# logged in, and only can set a few options. Logout necessary due to bwdc having
# a heart attack if you modify json file while logged in.
RUN --mount=type=secret,id=bw_clientid,uid=$BWUID \
    --mount=type=secret,id=bw_clientsecret,uid=$BWUID \
    BW_CLIENTID="$( cat /run/secrets/bw_clientid )" \
    && export BW_CLIENTID \
    && BW_CLIENTSECRET="$( cat /run/secrets/bw_clientsecret )" \
    && export BW_CLIENTSECRET \
    && BW_ORGUUID="${BW_CLIENTID#organization.}" \
    && BW_DATAFILE="$( bwdc data-file 2>/dev/null )" \
    && bwdc --version \
    && bwdc login \
    && bwdc config directory 2 \
    && bwdc logout \
    && jq -r \
      --arg orgid "${BW_ORGUUID}" \
      --arg googleDomain "$GOOGLE_DOMAIN" \
      --arg googleAdminUserEmail "$GOOGLE_ADMIN_USER_EMAIL" \
      --arg googleCustomer "$GOOGLE_CUSTOMER" \
      --arg googleServiceUserEmail "$GOOGLE_SERVICE_USER_EMAIL" \
      --arg googleSyncUsers "$GOOGLE_SYNC_USERS" \
      --arg googleSyncUserFilter "$GOOGLE_SYNC_USER_FILTER" \
      --arg googleSyncGroups "$GOOGLE_SYNC_GROUPS" \
      --arg googleSyncGroupFilter "$GOOGLE_SYNC_GROUP_FILTER" \
      --arg googleSyncRemoveDisabled "$GOOGLE_SYNC_REMOVE_DISABLED" \
      --arg googleSyncOverwriteExisting "$GOOGLE_SYNC_OVERWRITE_EXISTING" \
      --arg googleSyncLargeImport "$GOOGLE_SYNC_LARGE_IMPORT" \
      --slurpfile googleSync "$WORKING_DIR"/sync.json \
       'def tobool(f): if f == "true" then true elif f == "false" then false else f end; \
       .[$orgid].directoryConfigurations.gsuite.domain = $googleDomain \
       | .[$orgid].directoryConfigurations.gsuite.adminUser = $googleAdminUserEmail \
       | .[$orgid].directoryConfigurations.gsuite.clientEmail = $googleServiceUserEmail \
       | .[$orgid].directoryConfigurations.gsuite.customer = $googleCustomer \
       | .[$orgid].directorySettings.sync = $googleSync[0] \
       | .[$orgid].directorySettings.sync.users = tobool($googleSyncUsers) \
       | .[$orgid].directorySettings.sync.userFilter = $googleSyncUserFilter \
       | .[$orgid].directorySettings.sync.groups = tobool($googleSyncGroups) \
       | .[$orgid].directorySettings.sync.groupFilter = $googleSyncGroupFilter \
       | .[$orgid].directorySettings.sync.removeDisabled = tobool($googleSyncRemoveDisabled) \
       | .[$orgid].directorySettings.sync.overwriteExisting = tobool($googleSyncOverwriteExisting) \
       | .[$orgid].directorySettings.sync.largeImport = tobool($googleSyncLargeImport)' \
       "$BW_DATAFILE" > "$BW_DATAFILE".new \
    && cp "$BW_DATAFILE" "$BW_DATAFILE".old \
    && cp "$BW_DATAFILE".new "$BW_DATAFILE"
