# TODO: Remove temp debug workflow

name: DEBUG

permissions:
  contents: read

on:
  workflow_dispach:
  push:
    branches:
      actions/debug

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Debug
        run: set
