name: Build All Typed Images
description: Build all bwdc-$TYPE-$CONFNAME images

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'custom.conf'
      - 'gsuite/*.conf'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-bwdc-typed:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository under $GITHUB_WORKSPACE
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  #v4.2.2
        with:
          submodules: true

      - name: Build all typed images using ci.sh
        env:
          BW_CLIENTID: ${{ secrets.BW_CLIENTID }}
          BW_CLIENTSECRET: ${{ secrets.BW_CLIENTSECRET }}
        run: $GITHUB_WORKSPACE/bitwarden-directory-connector-containers/ci.sh -b
