name: Run All Typed Images
description: Run all bwdc-$TYPE-$CONFNAME images

on:
  workflow_dispatch:
    inputs:
      run_mode:
        required: true
        default: 'test'
        type: choice
        options:
          - config
          - test
          - sync

# The Github Action will not fail for unset secrets, so if you see some here
# for a type you are not using, it will not hurt to leave it
env:
  BW_CLIENTID: ${{ secrets.BW_CLIENTID }}
  BW_CLIENTSECRET: ${{ secrets.BW_CLIENTSECRET }}
  BW_GSUITEKEY: ${{ secrets.BW_GSUITEKEY }}
  # The following two should work as is for pulling from ghcr.io
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  # Use and update the following for other registries
  #REGISTRY_USER: ${{ secrets.IMAGE_REGISTRY_USER }}
  #REGISTRY_PASSWORD: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}

permissions:
  contents: read
  packages: read

jobs:
  run-all-typed:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository under $GITHUB_WORKSPACE
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  #v4.2.2
        with:
          submodules: true

      - name: Run all typed images using ci.sh with the mode specified
        run: $GITHUB_WORKSPACE/bitwarden-directory-connector-containers/ci.sh -r ${{ inputs.run_mode }}

