name: Build
description: Build bwdc-base image

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'Containerfile'
  workflow_dispatch:

permissions:
  contents: read

env:
  IMAGE_NAME: bwdc-base

jobs:
  build-bwdc-base:
    runs-on: ubuntu-latest
    outputs:
      built_image: ${{ steps.build_base_image.outputs.image }}
      built_tags: ${{ steps.build_base_image.outputs.tags }}

    steps:
      - name: Check-out repository under $GITHUB_WORKSPACE
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  #v4.2.2

      - name: Set bwdc-base version number based on the version of bwdc
        run: grep "^BWDC_VERSION=" "$GITHUB_WORKSPACE"/defaults.conf >> "$GITHUB_ENV"

      - name: Build image with buildah
        id: build_base_image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056  #v2.13
        with:
          # buildah-build always adds github.workspace, even if you already did it for them
          containerfiles: Containerfile
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.BWDC_VERSION }} ${{ github.sha }}
          extra-args: --build-arg-file defaults.conf
