# TODO Description

name: WIP Linting

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
    paths:
      '**/Containerfile'
      '**/*.md'
      '**/*.sh'
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository under $GITHUB_WORKSPACE
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
